sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      env: PYTHON=3.6 PYTHONWARNINGS=ignore

# public repository on Travis CI
install:
  - conda install -c conda-forge codecov

after_success:
  - codecov
