sudo: required

language:
  - python
  - cpp

# public repository on Travis CI
install:
  - pip install codecov

after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coverage report
