sudo: required

language:
  - python
  - cpp

python:
  - "3.6"
  - "3.7"

# public repository on Travis CI
install:
  - pip install coverage codecov pytest-cov codacy-coverage
  - pip install .

after_success:
  - codecov
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - coverage report
